config/routes.rb
Mironov::Application.routes.draw do

  root :to => 'main#index'

  get 'application/plan_create', :as => :plan_create
  get 'application/implementation_create', :as => :implementation_create

  devise_for :admin_users, ActiveAdmin::Devise.config do
    ActiveAdmin.routes(self)
  end

  devise_for :users do

    namespace :sweet do
      root :to => 'conference#index'
      get 'plan/next_day', :as => :plan_next_day
      get 'plan/prev_day', :as => :plan_prev_day

      get 'implementation/next_day', :as => :implementation_next_day
      get 'implementation/prev_day', :as => :implementation_prev_day

      get 'cash/next_day', :as => :cash_next_day
      get 'cash/prev_day', :as => :cash_prev_day

      get 'cashc/next_day', :as => :cashc_next_day
      get 'cashc/prev_day', :as => :cashc_prev_day

      get 'sold_done/index', :as => :sold_done

      match 'balance/' => 'balance#index'
      match 'cash/' => 'cash#index'
      match 'cashc/' => 'cashc#index'
      match 'implementation/' => 'implementation#index'
      match 'implementation/:id' => 'implementation#show', :as => :implementationshow
      match 'implementation/:id/all' => 'implementation#all', :as => :implementationall
      match 'plan/' => 'plan#index'
      match 'plan/:id' => 'plan#show', :as => :planshow
      match 'plan/:id/all' => 'plan#all', :as => :planall
      match 'conference/:id' => 'conference#show', :as => :conferenceshow
      match 'conference/' => 'conference#index'
      match 'set_date/' => 'application#save_cur_date', :as => :set_date

    end

    get 'plan/next_day', :as => :plan_next_day
    get 'plan/prev_day', :as => :plan_prev_day

    get 'implementation/next_day', :as => :implementation_next_day
    get 'implementation/prev_day', :as => :implementation_prev_day

    get 'cash/next_day', :as => :cash_next_day
    get 'cash/prev_day', :as => :cash_prev_day

    get 'cashc/next_day', :as => :cashc_next_day
    get 'cashc/prev_day', :as => :cashc_prev_day

    get 'sold_done/index', :as => :sold_done

    match 'balance/' => 'balance#index'
    match 'cash/' => 'cash#index'
    match 'cashc/' => 'cashc#index'
    match 'implementation/' => 'implementation#index'
    match 'implementation/:id' => 'implementation#show', :as => :implementationshow
    match 'implementation/:id/all' => 'implementation#all', :as => :implementationall
    match 'plan/' => 'plan#index'
    match 'plan/:id' => 'plan#show', :as => :planshow
    match 'plan/:id/all' => 'plan#all', :as => :planall
    match 'conference/:id' => 'conference#show', :as => :conferenceshow
    match 'conference/' => 'conference#index'
    match 'set_date/' => 'application#save_cur_date', :as => :set_date

  end

end

app/models/cash.rb
class Cash < ActiveRecord::Base
  self.table_name = 'KS'
  attr_accessible :N, :DAT, :KOD, :NAIM, :SUM, :BN1, :BN2, :BN3, :BN4, :BN5, :AWT, :BK1, :BK2, :BK3, :BK4, :BK5
end

app/controllers/cash_controller.rb
class CashController < BaseController
  def index
    @dat = Time.now  - 1.day
    if params[:day]
      @dat = Time.now - (params[:day].to_i + 1).day
    else
      @dat = Time.now - 1.day
    end
    
    if params[:year]

      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @dat.month, @dat.day )
    else
      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
      while @cash.size == 0 do
        @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
        @dat = @dat - 1.day
      end
    end

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
  end

  def prev_day

    @dat = params[:dat].to_date - 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @dat = params[:dat].to_date + 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end
end

app/controllers/sweet/cash_controller.rb
class Sweet::CashController < Sweet::BaseController
  def index
    @dat = Time.now  - 1.day
    if params[:day]
      @dat = Time.now - (params[:day].to_i + 1).day
    else
      @dat = Time.now - 1.day
    end
    
    if params[:year]

      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @dat.month, @dat.day )
    else
      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
      while @cash.size == 0 do
        @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
        @dat = @dat - 1.day
      end
    end

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
  end

  def prev_day

    @dat = params[:dat].to_date - 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @dat = params[:dat].to_date + 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end
end

app/helpers/cash_helper.rb
module CashHelper
end

app/views/cash/_cash_item.html.erb
<% if item.NAIM != "" %>
<tr>
  <td><%= item.NAIM %></td>
  <td><%= item.BN1 %></td>
  <td><%= item.BN2 %></td>
</tr>
<% end %>

app/views/cash/_table.html.erb
  <h3>Данные по банкам и по кассе - <%= Russian::strftime(cash.first.DAT.to_date, "%d %B %Y") if cash.first %></h3>
  <div class="row-fluid">
    <div class="span3">
      <ul class="pager">
        <li class="previous">
          <%= link_to Russian::strftime(dat - 1.day, "%d %B %Y"), cash_prev_day_url(:dat => dat), remote: true, :id => "prev_day" %>
        </li>

      </ul>
    </div>

    <div class="span6">
      <ul class="nav nav-pills">
        <li ><%= link_to Russian::strftime(Time.now - 1.day, "%d %B %Y"), cash_url()%></li>
        <li class="<%=params[:day] == '1' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 2.day, "%d %B %Y"), cash_url(:day => 1)%></li>
        <li class="<%=params[:day] == '2' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 3.day, "%d %B %Y"), cash_url(:day => 2)%></li>
        <li class="<%=params[:day] == '3' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 4.day, "%d %B %Y"), cash_url(:day => 3)%></li>
      </ul>
    </div>

    <div class="span3">
      <ul class="pager">
        <li class="next">
          <%= link_to Russian::strftime(dat + 1.day, "%d %B %Y"), cash_next_day_url(:dat => dat), remote: true, :id => "next_day" %>
        </li>
      </ul>
    </div>
  </div>

  <table class="table table-hover">
    <tr>
      <th>Наименование</th>
      <th>Сбербанк</th>
      <th>Россельхоз банк</th>
    </tr>
    <%= render :partial => "cash/cash_item", :collection => cash, :as => :item  %>
  </table>

app/views/cash/index.html.erb
<% if current_user.admin? %>
<div class="span12">
  <ul class="years">
    <% @m.each do |year| %>
        <li><%= link_to_unless_current year, cash_url(:year => year)%></li>
    <% end %>
  </ul>
  <div id="cash_table">
    <h3>Данные по банкам и по кассе - <%= Russian::strftime(@cash.first.DAT.to_date, "%d %B %Y") if @cash.first %></h3>
    <div class="row-fluid">
      <div class="span3">
        <ul class="pager">
          <li class="previous">
            <%= link_to Russian::strftime(@dat - 1.day, "%d %B %Y"), cash_prev_day_url(:dat => @dat), remote: true, :id => "prev_day" %>
          </li>

        </ul>
      </div>

      <div class="span6">
        <ul class="nav nav-pills">
          <li class="<%=params[:day] == nil ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 1.day, "%d %B %Y"), cash_url()%></li>
          <li class="<%=params[:day] == '1' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 2.day, "%d %B %Y"), cash_url(:day => 1)%></li>
          <li class="<%=params[:day] == '2' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 3.day, "%d %B %Y"), cash_url(:day => 2)%></li>
          <li class="<%=params[:day] == '3' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 4.day, "%d %B %Y"), cash_url(:day => 3)%></li>
        </ul>
      </div>

      <div class="span3">
        <ul class="pager">
          <li class="next">
            <%= link_to Russian::strftime(@dat + 1.day, "%d %B %Y"), cash_next_day_url(:dat => @dat), remote: true, :id => "next_day" %>
          </li>
        </ul>
      </div>
    </div>


    <table class="table table-hover">
    <tr>
      <th>Наименование</th>
      <th>Сбербанк</th>
      <th>Россельхоз банк</th>
    </tr>
    <%= render :partial => "cash/cash_item", :collection => @cash, :as => :item  %>
  </table>
</div>
</div>
<% else %>
    <h2>Недостаточно прав</h2>
<% end %>

app/views/cash/next_day.js.erb
$('#cash_table').hide( 'slide', {direction: 'right'}, 1500, {} );
$('#cash_table').html('<%=j render partial: 'cash/table', locals: { cash: @cash, dat: @dat } %>').fadeIn("slow")

app/views/cash/prev_day.js.erb
$('#cash_table').hide( 'slide', {direction: 'left'}, 1500, {} );
$('#cash_table').html('<%=j render partial: 'cash/table', locals: { cash: @cash, dat: @dat} %>').fadeIn("slow")