config/routes.rb
Mironov::Application.routes.draw do

  root :to => 'main#index'

  get 'application/plan_create', :as => :plan_create
  get 'application/implementation_create', :as => :implementation_create

  devise_for :admin_users, ActiveAdmin::Devise.config do
    ActiveAdmin.routes(self)
  end

  devise_for :users do

    namespace :sweet do
      root :to => 'conference#index'
      get 'plan/next_day', :as => :plan_next_day
      get 'plan/prev_day', :as => :plan_prev_day

      get 'implementation/next_day', :as => :implementation_next_day
      get 'implementation/prev_day', :as => :implementation_prev_day

      get 'cash/next_day', :as => :cash_next_day
      get 'cash/prev_day', :as => :cash_prev_day

      get 'cashc/next_day', :as => :cashc_next_day
      get 'cashc/prev_day', :as => :cashc_prev_day

      get 'sold_done/index', :as => :sold_done

      match 'balance/' => 'balance#index'
      match 'cash/' => 'cash#index'
      match 'cashc/' => 'cashc#index'
      match 'implementation/' => 'implementation#index'
      match 'implementation/:id' => 'implementation#show', :as => :implementationshow
      match 'implementation/:id/all' => 'implementation#all', :as => :implementationall
      match 'plan/' => 'plan#index'
      match 'plan/:id' => 'plan#show', :as => :planshow
      match 'plan/:id/all' => 'plan#all', :as => :planall
      match 'conference/:id' => 'conference#show', :as => :conferenceshow
      match 'conference/' => 'conference#index'
      match 'set_date/' => 'application#save_cur_date', :as => :set_date

    end

    get 'plan/next_day', :as => :plan_next_day
    get 'plan/prev_day', :as => :plan_prev_day

    get 'implementation/next_day', :as => :implementation_next_day
    get 'implementation/prev_day', :as => :implementation_prev_day

    get 'cash/next_day', :as => :cash_next_day
    get 'cash/prev_day', :as => :cash_prev_day

    get 'cashc/next_day', :as => :cashc_next_day
    get 'cashc/prev_day', :as => :cashc_prev_day

    get 'sold_done/index', :as => :sold_done

    match 'balance/' => 'balance#index'
    match 'cash/' => 'cash#index'
    match 'cashc/' => 'cashc#index'
    match 'implementation/' => 'implementation#index'
    match 'implementation/:id' => 'implementation#show', :as => :implementationshow
    match 'implementation/:id/all' => 'implementation#all', :as => :implementationall
    match 'plan/' => 'plan#index'
    match 'plan/:id' => 'plan#show', :as => :planshow
    match 'plan/:id/all' => 'plan#all', :as => :planall
    match 'conference/:id' => 'conference#show', :as => :conferenceshow
    match 'conference/' => 'conference#index'
    match 'set_date/' => 'application#save_cur_date', :as => :set_date

  end

end

app/controllers/plan_controller.rb
# encoding: utf-8
class PlanController < BaseController

  def index
    if params[:day]
      @workin_date.work_date_value = (Time.now - (params[:day].to_i + 1).day)

    end
    if params[:year]
      @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @workin_date.work_date_value.month, @workin_date.work_date_value.day )
    else
      @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
      while @plans.size == 0 do
        @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
        @workin_date.work_date_value = @workin_date.work_date_value - 1.day
      end
    end

    @workin_date.save!

    @p = Asrt.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

  end

  def next_day

    @workin_date.work_date_value = params[:dat].to_date + 1.day

    if params[:year]
      @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @workin_date.work_date_value.month, @workin_date.work_date_value.day )
    else
      @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
      while @plans.size == 0 do
        @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
        @workin_date.work_date_value = @workin_date.work_date_value - 1.day
      end
    end

    @workin_date.save!

    @p = Asrt.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
    respond_to do |format|
      format.html #render :action => :index
      format.js   # show_rec_horses.js.erb
    end

  end

  def prev_day

    @workin_date.work_date_value = params[:dat].to_date - 1.day

    if params[:year]
      @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @workin_date.work_date_value.month, @workin_date.work_date_value.day )
    else
      @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
      while @plans.size == 0 do
        @plans = Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
        @workin_date.work_date_value = @workin_date.work_date_value - 1.day
      end
    end

    @workin_date.save!

    @p = Asrt.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def show
    year = 2008 #Time.now.year - 1
    @plans = Asrt.where('N = ? AND YEAR(DAT) >= ?', params[:id], year).order("DAT DESC")
    @month_plans = []
    @days_plans_arr = []
    #@planday = (Time.now - 1.day)
    @planday = @workin_date.work_date_value
    @nowday = @planday
    pl = Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], @planday.year, @planday.month, @planday.day).first
    while pl == nil do
      @planday = @planday -1.day
      pl = Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], @planday.year, @planday.month, @planday.day).first
      @nowday = @planday

    end
    Time.now.year.to_i.downto 2008 do |year|
      if year == Time.now.year
        months = Time.now.month
      else
        months = 12
      end
      months.downto 1  do |month|
        @day = Time.new(year,month,1).end_of_month.day
        @month_plans << Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first.id if Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first
        @days_plans_arr << Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @nowday.day).first

      end
    end
    @month_plans << Asrt.where('N = ?', params[:id]).last.id
    @month_plans = Asrt.where('id IN (?)', @month_plans).order("DAT DESC")
  end

  def show2
    @month_plans_arr = []
    @days_plans_arr = []
    @planday = (Time.now - 1.day).day
    @nowday = @planday
    pl = Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], Time.now.year, Time.now.month, @planday).first
    while pl == nil do
      pl = Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], Time.now.year, Time.now.month, @planday).first
      @nowday = @planday
      @planday = @planday -1
    end
    Time.now.year.to_i.downto (Time.now.year - 1).to_i do |year|
      if year == Time.now.year
        months = Time.now.month
      else
        months = 12
      end
      months.downto 1  do |month|
        @day = Time.new(year,month,1).end_of_month.day
        @month_plans_arr << Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first
        @days_plans_arr << Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @nowday).first

      end
    end

    @plan_arr =[]
    @itog =[]
    @day_itog =[]
    @fact_arr =[]
    @month_arr =[]
    @years_count_arr  =[]
    @days_plan_arr =[]
    @days_fact_arr =[]
    @days_month_arr =[]

    @month_plans_arr.each do |m|
      if m
        @plan_arr << m.PLM.to_f if m
        @fact_arr << Asrt.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], m.DAT.to_date.year, m.DAT.to_date.month, (Time.now - 1.day).day).first.VRS.to_f if m
        @month_arr << Russian::strftime(m.DAT.to_date, "%d %B %Y") if m#.to_s+"  <br/>(<b>"+ Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) <= ? AND N = ?",m.DAT.to_date.year, m.DAT.to_date.month, params[:id]).sum("VRD").to_s+" тонн</b>)"
        @years_count_arr << Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) <= ? AND N = ?",m.DAT.to_date.year, m.DAT.to_date.month, params[:id]).sum("VRD").to_f if m
        #raise @years_count_arr.inspect
        @name = m.NAIM if m
        @itog << Asrt.where("YEAR(DAT) = ? AND MONTH(DAT) <= ? AND N = ?",m.DAT.to_date.year, m.DAT.to_date.month, params[:id]).sum("VRD").to_s+" т" if m
      end
    end


    @days_plans_arr.each do |d|
      @days_plan_arr << d.PLS.to_f if d
      @days_fact_arr << d.VRS.to_f if d
      @days_month_arr << Russian::strftime(d.DAT.to_date, "%d %B %y") if d#.to_s + '<br/>(<b>'+d.PLM.to_f.to_s+'</b>) тонн' if d
      @day_itog << d.PLM.to_f.to_s+' т' if d
    end


    @bar_graph = LazyHighCharts::HighChart.new('Area') do |f|
      f.xAxis([{:labels => {:rotation => 0, :align => 'right'}, :categories => @month_arr,
                :pointWidth => '25',
                :groupPadding => '0.9',
                :dataLabels => {
                    :enabled => true,
                    :rotation => 0,
                    :color => '#FFFFFF',
                    :align => 'right',
                    :x => -20,
                    :y => 3,
                }},
               {:labels => {:rotation => 0, :align => 'left'}, :categories => @itog, linkedTo: 0, opposite: true}])
      #f.options[:xAxis][:categories] = @month_arr
      f.series(:type=> 'bar', :name=>'План на месяц',:data=> @plan_arr,
               :pointWidth => '25',
               :groupPadding => '0.9',
               :dataLabels => {
                   :enabled => true,
                   :rotation => 0,
                   :color => '#FFFFFF',
                   :align => 'right',
                   :x => -20,
                   :y => 3,
               })
      f.series(:type=> 'bar', :name=>'Факт нарастающий',:data=> @fact_arr,
               :pointWidth => '25',
               :groupPadding => '0.9',
               :dataLabels => {
                   :enabled => true,
                   :rotation => 0,
                   :color => '#FFFFFF',
                   :align => 'right',
                   :x => -20,
                   :y => 3,
               })
      #f.plotOptions[{:bar => {  :dataLabels => { :enabled => true} }}],
      #f.plot_options({ :bar=> {:dataLabels => { :enabled => true}}})
      f.html_options[:style] = "width:100% !important; height:1200px !important;"
      f.tooltip({:shared => true, :crosshairs=> true,:valueSuffix => ' т'})
      f.legend({ layout: 'vertical',
                 align: 'right',
                 verticalAlign: 'top',
                 x: -150,
                 y: 0,
                 floating: true,
                 borderWidth: 1,
                 backgroundColor: '#FFFFFF',
                 shadow: true})
    end

    @line_graph = LazyHighCharts::HighChart.new('Area') do |f|
      f.options[:xAxis][:gridLineWidth] =  2
      f.series(:type=> 'spline', :name=>'План на месяц',:data=> @plan_arr.reverse)
      f.series(:type=> 'spline', :name=>'Факт нарастающий',:data=> @fact_arr.reverse)
      f.title({ :text=>"Динамика выполнения плана по месяцам - <b>" +@name+"</b>"})
      f.exporting({ :enabled => true})
      f.html_options[:style] = " !important; height:800px !important;"
      f.tooltip({:shared => true, :crosshairs=> true,:valueSuffix => ' т'})
      f.plot_options({ :line=> {:dataLabels => { :enabled => true}}})
      f.xAxis({:labels => {:rotation => 0, :align => 'right'}, :categories => @month_arr.reverse })
      f.legend({ layout: 'vertical',
                 align: 'right',
                 verticalAlign: 'top',
                 x: -150,
                 y: 0,

app/controllers/sweet/balance_controller.rb
class Sweet::BalanceController < Sweet::BaseController
  def index
    @balance = Balance.all
  end
end

app/controllers/sweet/base_controller.rb
class Sweet::BaseController < ApplicationController
  layout 'sweet'
  before_filter :authenticate_user!#, :exept => :admin
end

app/controllers/sweet/cash_controller.rb
class Sweet::CashController < Sweet::BaseController
  def index
    @dat = Time.now  - 1.day
    if params[:day]
      @dat = Time.now - (params[:day].to_i + 1).day
    else
      @dat = Time.now - 1.day
    end
    
    if params[:year]

      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @dat.month, @dat.day )
    else
      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
      while @cash.size == 0 do
        @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
        @dat = @dat - 1.day
      end
    end

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
  end

  def prev_day

    @dat = params[:dat].to_date - 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @dat = params[:dat].to_date + 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end
end

app/controllers/sweet/cashc_controller.rb
class Sweet::CashcController < Sweet::BaseController
  def index
    @dat = Time.now  - 1.day
    if params[:day]
      @dat = Time.now - (params[:day].to_i + 1).day
    else
      @dat = Time.now - 1.day
    end
    if params[:year]

      @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @dat.month, @dat.day )
    else
      @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
      while @cashc.size == 0 do
        @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
        @dat = @dat - 1.day
      end
    end

    @p = Cashc.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
  end

  def prev_day

    @dat = params[:dat].to_date - 1.day

    @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cashc.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @dat = params[:dat].to_date + 1.day

    @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cashc.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/sweet/base_helper.rb
module Sweet::BaseHelper
end

app/views/sweet/plan/_plan_item.html.erb
<tr >
  <td><%= link_to item.NAIM, sweet_planshow_url(item.N) %></td>
  <td class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion-plan" href="#item<%= item.N %>"><%= decimal_register item.PLM %></td>
  <td class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion-plan" href="#item<%= item.N %>"><%= decimal_register item.PLS %></td>
  <td class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion-plan" href="#item<%= item.N %>"><%= decimal_register item.VRS %></td>
  <td class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion-plan" href="#item<%= item.N %>"><%= decimal_register item.VRD %></td>
  <td class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion-plan" href="#item<%= item.N %>"><%= decimal_register item.OST %></td>
</tr>

<tr>
  <td colspan="6" class="more">
    <div id="item<%= item.N %>" class=" accordion-body collapse">
      <div class="plan-progress">
        <% if item.PLM.to_i > 0 %>
            План
            <div class="progress">

              <div class="bar bar-success" style="width: <%= number_to_percentage((item.PLS / item.PLM) *100, :precision => 0) %>;">
                 <%= number_to_percentage((item.PLS / item.PLM) *100, :precision => 0) %></div>
              <div class="bar bar-danger" style="width: <%= number_to_percentage( 100 - (item.PLS / item.PLM) *100, :precision => 0) %>;">
                <%= number_to_percentage(100 - (item.PLS / item.PLM) *100, :precision => 0) %></div>
            </div>

        <% else %>
            Нет данных
        <% end %>
      </div>
      <div class="fact-progress">
        <% if item.PLS.to_i > 0 %>
            Факт
            <div class="progress">
              <div class="bar bar-success" style="width: <%= number_to_percentage((item.VRS / item.PLS) *100, :precision => 0) %>;"><%= number_to_percentage((item.VRS / item.PLS) *100, :precision => 0) %></div>
              <div class="bar bar-danger" style="width: <%= number_to_percentage( 100 - (item.VRS / item.PLS) *100, :precision => 0) %>;"><%= number_to_percentage(100 - (item.VRS / item.PLS) *100, :precision => 0) %></div>
            </div>
        <% else %>
            Нет данных
        <% end %>
      </div>

    </div>
  </td>
</tr>

app/views/sweet/plan/_table.html.erb
<div class="row-fluid">
  <div class="span3">
    <ul class="pager">
      <li class="previous">
        <%= link_to Russian::strftime(dat - 1.day, "%d %B %Y"), sweet_plan_prev_day_url(:dat => dat), remote: true, :id => "prev_day" %>
      </li>

    </ul>
  </div>

  <div class="span6">
    <ul class="nav nav-pills">
      <li><%= link_to Russian::strftime(Time.now - 1.day, "%d %B %Y"), sweet_plan_url()%></li>
      <li class="<%=params[:day] == '1' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 2.day, "%d %B %Y"), sweet_plan_url(:day => 1)%></li>
      <li class="<%=params[:day] == '2' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 3.day, "%d %B %Y"), sweet_plan_url(:day => 2)%></li>
      <li class="<%=params[:day] == '3' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 4.day, "%d %B %Y"), sweet_plan_url(:day => 3)%></li>
    </ul>
  </div>

  <div class="span3">
    <ul class="pager">
      <li class="next">
        <%= link_to Russian::strftime(dat + 1.day, "%d %B %Y"), sweet_plan_next_day_url(:dat => dat), remote: true, :id => "next_day" %>
      </li>
    </ul>
  </div>
</div>
<% if plans.first %>
    <h3>Выполнение плана - <%= Russian::strftime(plans.first.DAT, "%d %B %Y") %></h3>
<% end %>
<table id="accordion-plan" class="table table-hover scrol">
  <tr>
    <th>Наименование</th>
    <th>План на месяц</th>
    <th>План нарастающий</th>
    <th>Факт нарастающий</th>
    <th>Дневная выработка</th>
    <th>Остатки</th>

  </tr>
  <%= render :partial => 'sweet/plan/plan_item', :collection => plans, :as => :item  %>
</table>

app/views/sweet/plan/all.html.erb
<% if current_user.admin? %>


    <div class="span12">
      <ul class="nav nav-tabs" id="myTab">
        <li><a href="#month">По месяцам</a></li>
        <li><a href="#day">По дням</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane" id="month">
          Динамика выполнения плана по месяцам - <b><%= @name %></b>
          <%= high_chart("monthBarGraph", @bar_graph) %>
          <%= high_chart("monthLineGraph", @line_graph) %>
        </div>
        <div class="tab-pane" id="day">
          Динамика выполнения плана по месяцам за <%=Time.now.day.to_s %> рабочих дней - <b><%= @name %></b>
          <%= high_chart("daysBarGraph", @days_bar_graph) %>
          <%= high_chart("daysLineGraph", @days_line_graph) %>
        </div>
      </div>
    </div>
<% else %>
    <h2>Недостаточно прав</h2>
<% end %>

app/views/sweet/plan/index.html.erb
<% if current_user.admin? %>
<div class="span12">

  <ul class="years">
  <% @m.each do |year| %>
  <li><%= link_to_unless_current year, sweet_plan_url(:year => year)%></li>
  <% end %>
  </ul>
  <br/>
  <br />
  <div id="plan_table">
  <div class="row-fluid">
    <div class="span3">
      <ul class="pager">
        <li class="previous">
          <%= link_to Russian::strftime(@workin_date.work_date_value - 1.day, "%d %B %Y"), sweet_plan_prev_day_url(:dat => @workin_date.work_date_value), remote: true, :id => "prev_day" %>
        </li>

      </ul>
    </div>

    <div class="span6">
      <ul class="nav nav-pills">
        <li class="<%=params[:day] == nil ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 1.day, "%d %B %Y"), sweet_plan_url()%></li>
        <li class="<%=params[:day] == '1' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 2.day, "%d %B %Y"), sweet_plan_url(:day => 1)%></li>
        <li class="<%=params[:day] == '2' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 3.day, "%d %B %Y"), sweet_plan_url(:day => 2)%></li>
        <li class="<%=params[:day] == '3' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 4.day, "%d %B %Y"), sweet_plan_url(:day => 3)%></li>
      </ul>
    </div>

    <div class="span3">
      <ul class="pager">
        <li class="next">
          <%= link_to Russian::strftime(@workin_date.work_date_value + 1.day, "%d %B %Y"), sweet_plan_next_day_url(:dat => @workin_date.work_date_value), remote: true, :id => "next_day" %>
        </li>
      </ul>
    </div>
  </div>
    <%= @workin_date.work_date_value %>
  <% if @plans.first %>
      <h3>Выполнение плана - <%= Russian::strftime(@plans.first.DAT, "%d %B %Y") %></h3>
  <% end %>
<table id="accordion-plan" class="table table-hover scrol">
  <tr>
    <th>Наименование</th>
    <th>План на месяц</th>
    <th>План нарастающий</th>
    <th>Факт нарастающий</th>
    <th>Дневная выработка</th>
    <th>Остатки</th>

  </tr>
  <%= render :partial => 'sweet/plan/plan_item', :collection => @plans, :as => :item  %>
</table>
  </div>
<%#= will_paginate @plans, :class => "flickr_pagination", :next_label => ">>", :previous_label => "<<" %>
</div>
<% else %>
    <h2>Недостаточно прав</h2>
<% end %>

app/views/sweet/plan/next_day.js.erb
$('#plan_table').hide( 'slide', {direction: 'right'}, 1500, {} );
$('#plan_table').html('<%=j render partial: 'plan/table', locals: { plans: @plans, dat: @workin_date.work_date_value } %>').fadeIn("slow")

app/views/sweet/plan/prev_day.js.erb
$('#plan_table').hide( 'slide', {direction: 'left'}, 1500, {} );
$('#plan_table').html('<%=j render partial: 'plan/table', locals: { plans: @plans, dat: @workin_date.work_date_value} %>').fadeIn("slow")