config/routes.rb
Mironov::Application.routes.draw do

  root :to => 'main#index'

  get 'application/plan_create', :as => :plan_create
  get 'application/implementation_create', :as => :implementation_create

  devise_for :admin_users, ActiveAdmin::Devise.config do
    ActiveAdmin.routes(self)
  end

  devise_for :users do

    namespace :sweet do
      root :to => 'conference#index'
      get 'plan/next_day', :as => :plan_next_day
      get 'plan/prev_day', :as => :plan_prev_day

      get 'implementation/next_day', :as => :implementation_next_day
      get 'implementation/prev_day', :as => :implementation_prev_day

      get 'cash/next_day', :as => :cash_next_day
      get 'cash/prev_day', :as => :cash_prev_day

      get 'cashc/next_day', :as => :cashc_next_day
      get 'cashc/prev_day', :as => :cashc_prev_day

      get 'sold_done/index', :as => :sold_done

      match 'balance/' => 'balance#index'
      match 'cash/' => 'cash#index'
      match 'cashc/' => 'cashc#index'
      match 'implementation/' => 'implementation#index'
      match 'implementation/:id' => 'implementation#show', :as => :implementationshow
      match 'implementation/:id/all' => 'implementation#all', :as => :implementationall
      match 'plan/' => 'plan#index'
      match 'plan/:id' => 'plan#show', :as => :planshow
      match 'plan/:id/all' => 'plan#all', :as => :planall
      match 'conference/:id' => 'conference#show', :as => :conferenceshow
      match 'conference/' => 'conference#index'
      match 'set_date/' => 'application#save_cur_date', :as => :set_date

    end

    get 'plan/next_day', :as => :plan_next_day
    get 'plan/prev_day', :as => :plan_prev_day

    get 'implementation/next_day', :as => :implementation_next_day
    get 'implementation/prev_day', :as => :implementation_prev_day

    get 'cash/next_day', :as => :cash_next_day
    get 'cash/prev_day', :as => :cash_prev_day

    get 'cashc/next_day', :as => :cashc_next_day
    get 'cashc/prev_day', :as => :cashc_prev_day

    get 'sold_done/index', :as => :sold_done

    match 'balance/' => 'balance#index'
    match 'cash/' => 'cash#index'
    match 'cashc/' => 'cashc#index'
    match 'implementation/' => 'implementation#index'
    match 'implementation/:id' => 'implementation#show', :as => :implementationshow
    match 'implementation/:id/all' => 'implementation#all', :as => :implementationall
    match 'plan/' => 'plan#index'
    match 'plan/:id' => 'plan#show', :as => :planshow
    match 'plan/:id/all' => 'plan#all', :as => :planall
    match 'conference/:id' => 'conference#show', :as => :conferenceshow
    match 'conference/' => 'conference#index'
    match 'set_date/' => 'application#save_cur_date', :as => :set_date

  end

end

app/controllers/implementation_controller.rb
# encoding: utf-8
class ImplementationController < BaseController
  PER_PAGE = 20

  def index
    if params[:day]
      @workin_date.work_date_value = (Time.now - (params[:day].to_i + 1).day)

    end
    if params[:year]
      @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", params[:year], @workin_date.work_date_value.month, @workin_date.work_date_value.day)
    else
      @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)


      while @implementations.size == 0 do
        @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
        @workin_date.work_date_value = @workin_date.work_date_value - 1.day

      end
      #raise @workin_date.work_date_value.inspect
    end

    @workin_date.save!

    @p = Implementation.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

  end
  def prev_day

    @workin_date.work_date_value = params[:dat].to_date - 1.day

    if params[:year]
      @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", params[:year], @workin_date.work_date_value.month, @workin_date.work_date_value.day)
    else
      @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
      while @implementations.size == 0 do
        @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
        @workin_date.work_date_value = @workin_date.work_date_value - 1.day
      end
    end

    @workin_date.save!

    @p = Implementation.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @workin_date.work_date_value = params[:dat].to_date + 1.day

    if params[:year]
      @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", params[:year], @workin_date.work_date_value.month, @workin_date.work_date_value.day)
    else
      @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
      while @implementations.size == 0 do
        @implementations = Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @workin_date.work_date_value.year, @workin_date.work_date_value.month, @workin_date.work_date_value.day)
        @workin_date.work_date_value = @workin_date.work_date_value - 1.day
      end
    end

    @workin_date.save!

    @p = Implementation.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def show
    year = 2008
    @plans = Implementation.where('N = ? AND YEAR(DAT) >= ?', params[:id], year).order("DAT DESC")

    @month_plans_arr = []
    @days_plans_arr = []
    @workin_date.work_date_value.year.to_i.downto 2008 do |year|
      if year == Time.now.year
        months = Time.now.month
      else
        months = 12
      end
      months.downto 1 do |month|
        if year == @workin_date.work_date_value.year && month == @workin_date.work_date_value.month
          @day = (@workin_date.work_date_value).day
          @dat = (@workin_date.work_date_value)
          @nowday = @dat.day
          impl = Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @dat.day).first
          #raise impl.inspect
          while impl == nil do
            impl = Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], @dat.year, @dat.month, @dat.day).first
            @nowday = @dat.day
            @dat = @dat - 1.day
            @day = @day - 1
          end

          @month_plans_arr << impl.id if impl
        else
          @day = Time.new(year, month, 1).end_of_month.day
          @month_plans_arr << Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first.id if Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first
        end


        #@month_plans << Implementation.where('N = ?', params[:id]).last.id
        @month_plans = Implementation.where('id IN (?)',@month_plans_arr).order("DAT DESC")
      end
    end
  end

  def show2

    @month_plans_arr = []
    @days_plans_arr = []
    Time.now.year.to_i.downto (Time.now.year - 1).to_i do |year|
      if year == Time.now.year
        months = Time.now.month
      else
        months = 12
      end
      months.downto 1 do |month|
        if year == Time.now.year && month == Time.now.month
          @day = (Time.now - 1.day).day
          @nowday = @day
          impl = Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first
          #raise impl.inspect
          while impl == nil do
            impl = Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first
            @nowday = @day
            @day = @day - 1
          end

          @month_plans_arr << impl
        else
          @day = Time.new(year, month, 1).end_of_month.day
          @month_plans_arr << Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, @day).first
        end


        #@days_plans_arr << Implementation.where('N = ? AND YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?', params[:id], year, month, Time.now.day).first
      end
    end

    @date_arr =[]
    @day_to_now_arr=[]

    @month_arr =[]
    @yearsumm = []

    @day_arr =[]
    @days_plan_arr =[]
    @days_fact_arr =[]
    @days_month_arr =[]
    #raise @month_plans_arr.inspect
    @month_plans_arr.each do |m|
      if m
        #@month_arr << m.SUMM.to_f if m
        @month_arr << Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND N = ?", m.DAT.to_date.year, m.DAT.to_date.month, params[:id]).sum("SUM").to_f if m
        s =Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ? AND N = ?", m.DAT.to_date.year, m.DAT.to_date.month, @nowday , params[:id]).first if m
        @day_to_now_arr << s.SUMM.to_f if s
        #raise m.inspect
        @date_arr << Russian::strftime(s.DAT.to_date, "%d %B %Y").to_s if s#+"  <br/>(<b>"+ Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ? AND N = ?",m.DAT.to_date.year, m.DAT.to_date.month, Time.now.day, params[:id]).first.SUMY.to_s+" тонн</b>)"
        @name = s.NAIM if s
        @yearsumm << Implementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ? AND N = ?", m.DAT.to_date.year, m.DAT.to_date.month, @nowday , params[:id]).first.SUMY.to_s + " т" if m
      end
    end
    #raise @month_arr.inspect

    #@days_plans_arr.each do |d|
    #  @days_plan_arr << d.PLM.to_f if d
    #  @days_fact_arr << d.VRS.to_f if d
    #  @days_month_arr << d.DAT.to_date if d
    #end

    #raise @name.inspect
    @bar_graph = LazyHighCharts::HighChart.new('Area') do |f|
      f.xAxis([{:labels => {:rotation => 0, :align => 'right'}, :categories => @date_arr},
               {:labels => {:rotation => 0, :align => 'left'}, :categories => @yearsumm, linkedTo: 0, opposite: true}])
      f.title({:text => "Динамика реализации - <b>" +@name +"</b>"})
      f.series(:type => 'bar',
               :name => 'Реализация за месяц', :data => @month_arr,
               :pointWidth => '25',
               :groupPadding => '0.9',
               :dataLabels => {
                   :enabled => true,
                   :rotation => 0,
                   :color => '#FFFFFF',
                   :align => 'right',
                   :x => -20,
                   :y => 3,
               })
      f.series(:type => 'bar', :name => 'Реализация на сегодняшний день('+@nowday.to_s+' рабочих дней) ',
               :data => @day_to_now_arr,
               :pointWidth => '25',
               :groupPadding => '0.9',
               :dataLabels => {
                   :enabled => true,
                   :rotation => 0,
                   :color => '#FFFFFF',
                   :align => 'right',
                   :x => -20,
                   :y => 3,
               })
      #f.plotOptions[{:bar => {  :dataLabels => { :enabled => true} }}],
      #f.plot_options({:bar => {:dataLabels => {:enabled => true}}})
      f.html_options[:style] = "width:100% !important; height:1200px !important;"
      f.tooltip({:shared => true, :crosshairs => true, :valueSuffix => ' тонн'})
      f.legend({layout: 'vertical',
                align: 'right',
                verticalAlign: 'top',
                x: -150,
                y: 0,
                floating: true,
                borderWidth: 1,
                backgroundColor: '#FFFFFF',
                shadow: true})
    end

    @line_graph = LazyHighCharts::HighChart.new('Area') do |f|
      f.options[:xAxis][:gridLineWidth] = 1
      f.series(:type => 'spline', :name => 'Реализация за месяц', :data => @month_arr.reverse)
      f.series(:type => 'spline', :name => 'Реализация на сегодняшний день('+@nowday.to_s+' рабочих дней) ', :data => @day_to_now_arr.reverse)

app/controllers/sweet/balance_controller.rb
class Sweet::BalanceController < Sweet::BaseController
  def index
    @balance = Balance.all
  end
end

app/controllers/sweet/base_controller.rb
class Sweet::BaseController < ApplicationController
  layout 'sweet'
  before_filter :authenticate_user!#, :exept => :admin
end

app/controllers/sweet/cash_controller.rb
class Sweet::CashController < Sweet::BaseController
  def index
    @dat = Time.now  - 1.day
    if params[:day]
      @dat = Time.now - (params[:day].to_i + 1).day
    else
      @dat = Time.now - 1.day
    end
    
    if params[:year]

      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @dat.month, @dat.day )
    else
      @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
      while @cash.size == 0 do
        @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
        @dat = @dat - 1.day
      end
    end

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
  end

  def prev_day

    @dat = params[:dat].to_date - 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @dat = params[:dat].to_date + 1.day

    @cash = Cash.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cash.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end
end

app/controllers/sweet/cashc_controller.rb
class Sweet::CashcController < Sweet::BaseController
  def index
    @dat = Time.now  - 1.day
    if params[:day]
      @dat = Time.now - (params[:day].to_i + 1).day
    else
      @dat = Time.now - 1.day
    end
    if params[:year]

      @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",params[:year], @dat.month, @dat.day )
    else
      @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
      while @cashc.size == 0 do
        @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?",@dat.year, @dat.month, @dat.day )
        @dat = @dat - 1.day
      end
    end

    @p = Cashc.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end
  end

  def prev_day

    @dat = params[:dat].to_date - 1.day

    @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cashc.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

  def next_day

    @dat = params[:dat].to_date + 1.day

    @cashc = Cashc.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ?", @dat.year, @dat.month, @dat.day )

    @p = Cashc.select("DISTINCT YEAR(DAT) AS YEARS")

    @m =[]

    @p.each do |o|
      @m << o[:YEARS].to_i
    end

    respond_to do |format|
      format.html #(render :action => :index)
      format.js   # show_rec_horses.js.erb
    end
  end

end

app/helpers/implementation_helper.rb
module ImplementationHelper
end

app/helpers/sweet/base_helper.rb
module Sweet::BaseHelper
end

app/views/sweet/implementation/_implementation_item.html.erb
<tr>
  <td><%= link_to item.NAIM, sweet_implementationshow_url(item.N) %></td>
  <td><%= int_register item.SUM %></td>
  <td><%= int_register item.SUMM %></td>
  <td><%= int_register item.SUMY %></td>
</tr>

app/views/sweet/implementation/_table.html.erb
<div class="row-fluid">
  <div class="span3">
    <ul class="pager">
      <li class="previous">
        <%= link_to Russian::strftime(dat - 1.day, "%d %B %Y"), sweet_implementation_prev_day_url(:dat => dat), remote: true, :id => "prev_day" %>
      </li>

    </ul>
  </div>

  <div class="span6">
    <ul class="nav nav-pills">
      <li ><%= link_to Russian::strftime(Time.now - 1.day, "%d %B %Y"), sweet_implementation_url()%></li>
      <li class="<%=params[:day] == '1' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 2.day, "%d %B %Y"), sweet_implementation_url(:day => 1)%></li>
      <li class="<%=params[:day] == '2' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 3.day, "%d %B %Y"), sweet_implementation_url(:day => 2)%></li>
      <li class="<%=params[:day] == '3' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 4.day, "%d %B %Y"), sweet_implementation_url(:day => 3)%></li>
    </ul>
  </div>

  <div class="span3">
    <ul class="pager">
      <li class="next">
        <%= link_to Russian::strftime(dat + 1.day, "%d %B %Y"), sweet_implementation_next_day_url(:dat => dat), remote: true, :id => "next_day" %>
      </li>
    </ul>
  </div>
</div>
  <% if implementations.first %>
      <h3>Реализация продукции  - <%= Russian::strftime(implementations.first.DAT.to_date, "%d %B %Y")%></h3>
  <% end %>
  <table class="table table-hover">
    <tr>
      <th>Наименование</th>
      <th>Реализация за день</th>
      <th>Реализация с начала месяца</th>
      <th>Реализация c начала года</th>
    </tr>

    <%= render :partial => 'sweet/implementation/implementation_item', :collection => implementations, :as => :item  %>
  </table>
</div>

app/views/sweet/implementation/index.html.erb
<% if current_user.admin? %>
<div class="span12">
  <ul class="years">
    <% @m.each do |year| %>
        <li><%= link_to_unless_current year, sweet_implementation_url(:year => year)%></li>
    <% end %>
  </ul>
  <br/>
  <br/>

  <div id="implementation_table">
    <div class="row-fluid">
      <div class="span3">
        <ul class="pager">
          <li class="previous">
            <%= link_to Russian::strftime(@workin_date.work_date_value - 1.day, "%d %B %Y"), sweet_implementation_prev_day_url(:dat => @workin_date.work_date_value), remote: true, :id => "prev_day" %>
          </li>

        </ul>
      </div>

      <div class="span6">
        <ul class="nav nav-pills">
          <li class="<%=params[:day] == nil ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 1.day, "%d %B %Y"), sweet_implementation_url()%></li>
          <li class="<%=params[:day] == '1' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 2.day, "%d %B %Y"), sweet_implementation_url(:day => 1)%></li>
          <li class="<%=params[:day] == '2' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 3.day, "%d %B %Y"), sweet_implementation_url(:day => 2)%></li>
          <li class="<%=params[:day] == '3' ? 'active' : '' %>"><%= link_to Russian::strftime(Time.now - 4.day, "%d %B %Y"), sweet_implementation_url(:day => 3)%></li>
        </ul>
      </div>

      <div class="span3">
        <ul class="pager">
          <li class="next">
            <%= link_to Russian::strftime(@workin_date.work_date_value + 1.day, "%d %B %Y"), sweet_implementation_next_day_url(:dat => @workin_date.work_date_value), remote: true, :id => "next_day" %>
          </li>
        </ul>
      </div>
    </div>

  <% if @implementations.first %>
  <h3>Реализация продукции  - <%= Russian::strftime(@implementations.first.DAT.to_date, "%d %B %Y")%></h3>
      <% end %>
  <table class="table table-hover">
    <tr>
      <th>Наименование</th>
      <th>Реализация за день</th>
      <th>Реализация с начала месяца</th>
      <th>Реализация c начала года</th>
    </tr>

    <%= render :partial => 'sweet/implementation/implementation_item', :collection => @implementations, :as => :item  %>
  </table>
    </div>
    </div>
<% else %>
    <h2>Недостаточно прав</h2>
<% end %>

app/views/sweet/implementation/show.html.erb
<% if current_user.admin? %>
    <div class="span12">
      <p><%= link_to "Данные за все время", sweet_implementationall_url(params[:id]) %></p>
      <ul class="nav nav-tabs" id="myTab">
        <li><a href="#day">По дням</a></li>
        <li><a href="#month">По месяцам</a></li>

      </ul>

      <div class="tab-content">
        <div class="tab-pane" id="month">

          <%
             #max_pls_m = @month_plans.maximum('PLM')
             max_summ_m = @month_plans.maximum('SUMM')
             #if max_pls_m > max_vrs_m
             #	@max_m = max_pls_m
             #else
             #	@max_m = max_vrs_m
             #end
             @max_m = max_summ_m
             @d = "scroller"
          %>
          <% @month_plans.each do |plan| %>
              <div class="row-fluid <%= @d %>">
                <div class="span12">
                  <% if @d != 1 %>
                      Динамика реализации(По месяцам) - <b><%= @month_plans.first.NAIM %></b>
                      <br/>
                      <br/>
                  <% end %>
                  <div class="row-fluid ">
                    <div class="span2">
                      <% if @d != 1 %>
                          Дата <br/> <br/>
                      <% end %>
                      <%= Russian::strftime(plan.DAT, "%d %B %Y") %></div>
                    <div class="span8">
                      <% if @d != 1 %>
                          <span class="label label-success">Реализация за месяц</span>
                      <span class="label label-important">Реализация на сегодняшний день(<%= @nowday %>
                        рабочих дней) </span> <br/><br/>
                      <% end %>
                      <div class="progress progress-success">

                        <div class="bar" style="width: <%= number_to_percentage((plan.SUMM / @max_m.to_f) *100, :precision => 0) %>">
                          <p><%= int_register plan.SUMM %> кг</p></div>
                      </div>
                      <% if SwImplementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ? AND N = ?", plan.DAT.to_date.year, plan.DAT.to_date.month, @nowday, plan.N).first
                           sum =SwImplementation.where("YEAR(DAT) = ? AND MONTH(DAT) = ? AND DAY(DAT) = ? AND N = ?", plan.DAT.to_date.year, plan.DAT.to_date.month, @nowday, plan.N).first.SUMM.to_f
                         else
                           sum = 0
                         end
                      %>
                      <div class="progress progress-danger">
                        <div class="bar" style="width: <%= number_to_percentage((sum / @max_m.to_f) *100, :precision => 0) %>"><p><%= int_register sum.to_i %> кг</p>
                        </div>
                      </div>
                    </div>
                    <div class="span2">
                      <% if @d != 1 %>
                          Реализация за год <br/><br/>
                      <% end %>
                      <%= int_register plan.SUMY %> кг
                    </div>
                  </div>
                </div>
              </div>
              <br/>
              <% @d = 1 %>
          <% end %>
          <div class="row-fluid bottomblok"></div>
          <%#= high_chart("monthBarGraph", @bar_graph) %>
          <%#= high_chart("monthLineGraph", @line_graph) %>
        </div>
        <div class="tab-pane" id="day">
          <%
             @max = @plans.where('DAY(DAT) = ?', @nowday).maximum('SUMM')
             @d = "scroller"
          %>

          <br/>
          <% @plans.where('DAY(DAT) = ?', @nowday).each do |plan| %>
              <%#= plan.inspect %>
              <div class="row-fluid <%= @d %>">
                <div class="span12">
                  <% if @d != 1 %>

                      Динамика выполнения плана по месяцам(по дням) за <%= @nowday %> рабочих дней -
                      <b><%= @plans.first.NAIM %></b><br/> <br/>
                  <% end %>
                  <div class="row-fluid ">
                    <div class="span2">
                      <% if @d != 1 %>
                          Дата <br/> <br/>
                      <% end %>
                      <%= Russian::strftime(plan.DAT, "%d %B %Y") %></div>
                    <div class="span8">
                      <% if @d != 1 %>
                          <span class="label label-success">Реализация на сегодняшний день</span> <br/><br/>
                      <% end %>
                      <div class="progress progress-success">
                        <div class="bar" style="width: <%= number_to_percentage((plan.SUMM.to_f / @max.to_f) *100, :precision => 0) %>">
                          <p><%= int_register plan.SUMM %> кг </p></div>
                      </div>
                    </div>
                    <div class="span2">
                      <% if @d != 1 %>
                          Реализация за год <br/><br/>
                      <% end %>
                      <%= int_register plan.SUMY %> кг
                    </div>
                  </div>
                </div>
              </div>
              <br/>
              <% @d = 1 %>
          <% end %>
          <div class="row-fluid bottomblok"></div>

<%#= high_chart("daysBarGraph", @days_bar_graph) %>

<%#= high_chart("daysLineGraph", @day_sbar_graph) %>
        </div>
      </div>
    </div>
<% else %>
    <h2>Недостаточно прав</h2>
<% end %>